# Generated by Django 4.1.2 on 2022-12-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDtl',
            fields=[
                ('price', models.CharField(db_column='PRICE', max_length=15)),
                ('vat', models.CharField(db_column='VAT', max_length=15)),
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bill_dtls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusid', models.IntegerField(db_column='CUSID', primary_key=True, serialize=False)),
                ('cusname', models.CharField(blank=True, db_column='CUSNAME', max_length=20, null=True)),
                ('cntno', models.IntegerField(blank=True, db_column='CNTNO', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_no', models.IntegerField(db_column='FOOD_NO', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=30, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.IntegerField(db_column='ORDER_NO', primary_key=True, serialize=False)),
                ('no_of_item', models.IntegerField(db_column='NO_OF_ITEM')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('no_of_item', models.IntegerField(db_column='NO_OF_ITEM', primary_key=True, serialize=False)),
                ('oreder_time', models.CharField(db_column='OREDER_TIME', max_length=20)),
            ],
            options={
                'db_table': 'order_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rid', models.IntegerField(db_column='RID', primary_key=True, serialize=False)),
                ('rname', models.CharField(blank=True, db_column='RNAME', max_length=20, null=True)),
                ('conatactno', models.IntegerField(blank=True, db_column='CONATACTNO', null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('rname', models.CharField(db_column='RNAME', max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'restaurant_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('food_no', models.ForeignKey(db_column='FOOD_NO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Royal_Trinite.food')),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
            ],
            options={
                'db_table': 'food_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('wid', models.IntegerField(db_column='WID', primary_key=True, serialize=False)),
                ('wname', models.CharField(blank=True, db_column='WNAME', max_length=30, null=True)),
                ('cusid', models.ForeignKey(db_column='CUSID', on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.customer')),
                ('order_no', models.ForeignKey(db_column='ORDER_NO', on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.order')),
            ],
            options={
                'db_table': 'waiter',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='food',
            name='order_no',
            field=models.ForeignKey(blank=True, db_column='ORDER_NO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rid',
            field=models.ForeignKey(blank=True, db_column='RID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.restaurant'),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.IntegerField(db_column='CHEF_ID', primary_key=True, serialize=False)),
                ('chef_name', models.CharField(blank=True, db_column='CHEF_NAME', max_length=30, null=True)),
                ('order_no', models.ForeignKey(db_column='ORDER_NO', on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.order')),
            ],
            options={
                'db_table': 'chef',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.IntegerField(db_column='BILL_NO', primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('order_dtl', models.CharField(blank=True, db_column='ORDER_DTL', max_length=30, null=True)),
                ('cus', models.ForeignKey(blank=True, db_column='CUS_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Royal_Trinite.customer')),
            ],
            options={
                'db_table': 'bill',
                'managed': True,
            },
        ),
    ]
